/*** Copyright (C) 2019-2021 ZaidaTek and Andreas Riebesehl
**** This work is licensed under: Creative Commons Attribution-NoDerivatives 4.0 International Public License
**** For full license text, please visit: https://creativecommons.org/licenses/by-nd/4.0/legalcode
***/
#ifndef ZUI__DEFAULTS_H_INCLUDED
#define ZUI__DEFAULTS_H_INCLUDED

#define ZUI_DEFAULT_FLAG ZUI_FLAG_NONE

#define ZUI_DEFAULT_ELEMENT_FLAG (ZUI_ELEMENT_FLAG_SHOW | ZUI_ELEMENT_FLAG_COLLIDE)

#define ZUI_DEFAULT_STYLE ZUI_ELEMENT_STYLE_NONE

#define ZUI_DEFAULT_LABEL_BORDER_SIZE 0
#define ZUI_DEFAULT_BUTTON_BORDER_SIZE 1
#define ZUI_DEFAULT_BOX_BORDER_SIZE 1

#define ZUI_DEFAULT_UI_COLOR_DISABLED_BACK ZUI_COLOR_LIGHT_GRAY
#define ZUI_DEFAULT_UI_COLOR_NORMAL_BACK ZUI_COLOR_LIGHT_GRAY
#define ZUI_DEFAULT_UI_COLOR_HOVER_BACK ZUI_COLOR_TRANSPARENT
#define ZUI_DEFAULT_UI_COLOR_PRESS_BACK ZUI_COLOR_GRAY
#define ZUI_DEFAULT_UI_COLOR_RELEASE_BACK ZUI_COLOR_MEDIUM_GRAY
#define ZUI_DEFAULT_UI_COLOR_FOCUS_BACK ZUI_COLOR_TRANSPARENT

#define ZUI_DEFAULT_UI_COLOR_DISABLED_FRONT ZUI_COLOR_GRAY
#define ZUI_DEFAULT_UI_COLOR_NORMAL_FRONT ZUI_COLOR_BLACK
#define ZUI_DEFAULT_UI_COLOR_HOVER_FRONT ZUI_COLOR_TRANSPARENT
#define ZUI_DEFAULT_UI_COLOR_PRESS_FRONT ZUI_COLOR_WHITE
#define ZUI_DEFAULT_UI_COLOR_RELEASE_FRONT ZUI_COLOR_WHITE
#define ZUI_DEFAULT_UI_COLOR_FOCUS_FRONT ZUI_COLOR_TRANSPARENT

#define ZUI_DEFAULT_UI_COLOR_DISABLED_BORDER ZUI_COLOR_GRAY
#define ZUI_DEFAULT_UI_COLOR_NORMAL_BORDER ZUI_COLOR_BLACK
#define ZUI_DEFAULT_UI_COLOR_HOVER_BORDER ZUI_COLOR_YELLOW
#define ZUI_DEFAULT_UI_COLOR_PRESS_BORDER ZUI_COLOR_TRANSPARENT
#define ZUI_DEFAULT_UI_COLOR_RELEASE_BORDER ZUI_COLOR_TRANSPARENT
#define ZUI_DEFAULT_UI_COLOR_FOCUS_BORDER ZUI_COLOR_WHITE

/*
#define ZUI_DEFAULT_FONT_PATH "res/OpenSans/OpenSans-Regular.ttf"

#define ZUI_DEFAULT_BOX_PROPERTIES_COLOR 0x1b1b1bdf
#define ZUI_DEFAULT_BOX_PROPERTIES_FRAMECOLOR 0xfafafaff
#define ZUI_DEFAULT_BOX_PROPERTIES_FRAMESIZE 1


#define ZUI_DEFAULT_CHARSET_PROPERTIES_FONTPATH ZUI_DEFAULT_FONT_PATH
#define ZUI_DEFAULT_CHARSET_PROPERTIES_FONTSIZE 16
#define ZUI_DEFAULT_CHARSET_PROPERTIES_COLOR 0xffffffff
#define ZUI_DEFAULT_CHARSET_PROPERTIES_FILLCOLOR 0x000000ff
#define ZUI_DEFAULT_CHARSET_PROPERTIES_LINEMARGIN 0
#define ZUI_DEFAULT_CHARSET_PROPERTIES_STYLE JUICYGUI_CHARSET_STYLE_NORMAL
*/
#endif // ZUI__DEFAULTS_H_INCLUDED
