/*** Copyright (C) 2019-2025 ZaidaTek, Andreas Riebesehl
**** This work is licensed under: Creative Commons Attribution-NoDerivatives 4.0 International Public License
**** For full license text, please visit: https://creativecommons.org/licenses/by-nd/4.0/legalcode
***/
#ifndef ZDX_DEFINE_H_INCLUDED
#define ZDX_DEFINE_H_INCLUDED

#include "ZDX__SHARED__DEF.h"
#include "ZDX__SHARED__UALL.h"

#define ZDX_FLAG_NONE 0x0
#define ZDX_TYPE_NONE 0x0

#define ZDX_RUNTIME_BUFFER_SERIAL 1048576

#define ZDX_CHANNEL_SPEED_NONE 0

#define ZDX_INTERFACE_TYPE_SERIAL 0x1
#define ZDX_INTERFACE_SERIAL_BAUD 2000000
#define ZDX_INTERFACE_SERIAL_BUFFER 65536
#define ZDX_INTERFACE_SERIAL_HEADER 0x800000
#define ZDX_INTERFACE_SERIAL_INDEX 0x400000
#define ZDX_INTERFACE_SERIAL_FLAG_RX 0x3fffff

#define ZDX_DEVICE_FLAG_UNBUFFERED 0x1
#define ZDX_DEVICE_TYPE_AT328P 0x100

#define ZDX_DIAGRAM_FLAG_TRIGGER 0x1
#define ZDX_DIAGRAM_FLAG_CURSOR_DATA 0x2
#define ZDX_DIAGRAM_FLAG_GRID 0x4
#define ZDX_DIAGRAM_FLAG_GRIDREF_DATA 0x8
#define ZDX_DIAGRAM_FLAG_FLIP_H 0x10
#define ZDX_DIAGRAM_FLAG_FLIP_V 0x20
#define ZDX_DIAGRAM_COLOR_PLOT_1 0xffff00ff
#define ZDX_DIAGRAM_COLOR_PLOT_2 0x0080ffff
#define ZDX_DIAGRAM_COLOR_PLOT_3 0xff0000ff
#define ZDX_DIAGRAM_COLOR_PLOT_4 0x00ff00ff
#define ZDX_DIAGRAM_COLOR_PLOT_5 0xff8000ff
#define ZDX_DIAGRAM_COLOR_PLOT_6 0xffffffff
#define ZDX_DIAGRAM_COLOR_PLOT_7 0x004000ff
#define ZDX_DIAGRAM_COLOR_PLOT_8 0x400080ff
#define ZDX_DIAGRAM_COLOR_PLOTS 8
#define ZDX_DIAGRAM_COLOR_BACKGROUND 0x000000ff
#define ZDX_DIAGRAM_COLOR_TRIGGER 0xffffffff
#define ZDX_DIAGRAM_COLOR_CURSOR_DATA 0x800000ff
#define ZDX_DIAGRAM_COLOR_CURSOR_FIRST 0xbfbfbfff
#define ZDX_DIAGRAM_COLOR_CURSOR_SECOND 0xbfbfbfff
#define ZDX_DIAGRAM_COLOR_GRID_MAJOR 0x303030ff
#define ZDX_DIAGRAM_COLOR_GRID_MINOR 0x101010ff
#define ZDX_DIAGRAM_DEFAULT_FLAG (ZDX_DIAGRAM_FLAG_TRIGGER | ZDX_DIAGRAM_FLAG_CURSOR_DATA | ZDX_DIAGRAM_FLAG_GRID | ZDX_DIAGRAM_FLAG_GRIDREF_DATA)

#define ZDX_TRIGGER_TYPE_RISING 0x1
#define ZDX_TRIGGER_TYPE_FALLING 0x2

#endif // ZDX_DEFINE_H_INCLUDED
