/*** Copyright (C) 2019-2020 ZaidaTek and Andreas Riebesehl
**** This work is licensed under: Creative Commons Attribution-NoDerivatives 4.0 International Public License
**** For full license text, please visit: https://creativecommons.org/licenses/by-nd/4.0/legalcode
***/
#ifndef ZTK__DEFAULTS_H_INCLUDED
#define ZTK__DEFAULTS_H_INCLUDED

//#define ZTK_DEFAULT_RES "res"
//#define ZTK_DEFAULT_RESPATH "../"

#define ZTK_DEFAULT_BUFFER_EVENTS 16384
#define ZTK_DEFAULT_BUFFER_DRAWS_SINGLE 8192
#define ZTK_DEFAULT_BUFFER_INPUT_TEXT 4

#define ZTK_DEFAULT_EVENT_DISABLED ZTK_HID_NONE
#define ZTK_DEFAULT_EVENT_ENABLED ZTK_HID_ALL
#define ZTK_DEFAULT_EVENT_CAPTURE ZTK_HID_ALL
#define ZTK_DEFAULT_EVENT_PUMP (ZTK_HID_MOUSE | ZTK_HID_KEY)
#define ZTK_DEFAULT_EVENT_RAW (ZTK_HID_ALL & ~(ZTK_HID_WINDOW))
#define ZTK_DEFAULT_EVENT_FLAG (ZTK_EVENT_FLAG_SIMPLE)

#define ZTK_DEFAULT_DRAW_FLAG ZTK_DRAW_FLAG_ENABLED

#define ZTK_DEFAULT_PALETTE_USER ZTM_PALETTE_RGBA
#define ZTK_DEFAULT_WINDOW_TITLE "Default ZTK Engine Window Title"
//#define ZTK_DEFAULT_WINDOW_ICON ZTK_DEFAULT_RES "/" "icon.ico"
#define ZTK_DEFAULT_WINDOW_ICON_INTEGRATED_ID 101
#define ZTK_DEFAULT_WINDOW_ICON_INTEGRATED "icon.ico"
#define ZTK_DEFAULT_WINDOW_TIME_RESOLUTION 1
#define ZTK_DEFAULT_WINDOW_TIME_BASE 5
#define ZTK_DEFAULT_WINDOW_INPUT_FLAG ZTK_WINDOW_FLAG_NONE
#define ZTK_DEFAULT_WINDOW_IDLE_FLAG (ZTK_WINDOW_IDLE_HOLDOFF)
#define ZTK_DEFAULT_WINDOW_IDLE_HOLDOFF (ZTK_DEFAULT_WINDOW_TIME_BASE - 1)
#define ZTK_DEFAULT_WINDOW_HEARTBEAT ((3 * ZTK_DEFAULT_WINDOW_TIME_BASE) - 1)
#define ZTK_DEFAULT_WINDOW_BACKGROUND_FLAG ZTK_WINDOW_BACKGROUND_ENABLED
#define ZTK_DEFAULT_WINDOW_BACKGROUND_COLOR 0x000000ff
#define ZTK_DEFAULT_WINDOW_POS_X 64
#define ZTK_DEFAULT_WINDOW_POS_Y 64
#define ZTK_DEFAULT_WINDOW_WIDTH 256
#define ZTK_DEFAULT_WINDOW_HEIGHT 128
#define ZTK_DEFAULT_WINDOW_TEXT_FLAG 0x0
#define ZTK_DEFAULT_WINDOW_TEXT_STYLE ZTM_FONT_STYLE_NORMAL
#define ZTK_DEFAULT_WINDOW_TEXT_SIZE 18
#define ZTK_DEFAULT_WINDOW_TEXT_COLOR 0xffffffff
#ifdef ZTM_ARCH__WIN
#define ZTK_DEFAULT_WINDOW_TEXT_FONT "MS Sans Serif"
#define ZTK_DEFAULT_WINDOW_TEXT_FONT_TYPE ZTM_FONT_TYPE_NONE
#define ZTK_DEFAULT_WINDOW_TEXT_FONT_SOURCE NULL
#else
#define ZTK_DEFAULT_WINDOW_TEXT_FONT "Open Sans"
#define ZTK_DEFAULT_WINDOW_TEXT_FONT_TYPE ZTM_FONT_TYPE_TTF
#define ZTK_DEFAULT_WINDOW_TEXT_FONT_SOURCE "OpenSans/OpenSans-Regular.ttf" //ZTK_DEFAULT_RES "/" "OpenSans/OpenSans-Regular.ttf"
#endif // ZTM_ARCH__WIN

#endif // ZTK__DEFAULTS_H_INCLUDED
