/*** Copyright (C) 2019-2020 ZaidaTek and Andreas Riebesehl
**** This work is licensed under: Creative Commons Attribution-NoDerivatives 4.0 International Public License
**** For full license text, please visit: https://creativecommons.org/licenses/by-nd/4.0/legalcode
***/
#ifndef ZTK__DEFINES_H_INCLUDED
#define ZTK__DEFINES_H_INCLUDED

#define ZTK_KEY_SIZE_LENGTH 0x100
#define ZTK_KEY_SIZE_SHIFT 3
#define ZTK_KEY_SIZE_UNIT 8
#define ZTK_KEY_SIZE_UNITS (ZTK_KEY_SIZE_LENGTH / ZTK_KEY_SIZE_UNIT)

#define ZTK_FLAG_NONE 0x0

#define ZTK_EVENT_FLAG_NONE ZTK_FLAG_NONE
#define ZTK_EVENT_FLAG_SIMPLE 0x1
#define ZTK_EVENT_FLAG_FAST 0x2
#define ZTK_EVENT_FLAG_INIT_HEARTBEAT 0x10

#define ZTK_DRAW_FLAG_NONE 0x0
#define ZTK_DRAW_FLAG_ENABLED 0x1
#define ZTK_DRAW_FLAG_UNBUFFERED 0x10
#define ZTK_DRAW_FLAG_NULLDEST 0x100

#define ZTK_DRAW_TYPE_SPRITE 0x1
#define ZTK_DRAW_TYPE_SURFACE 0x2
#define ZTK_DRAW_TYPE_TEXT 0x4

#define ZTK_WINDOW_FLAG_NONE 0x0
#define ZTK_WINDOW_FLAG_USER 0x1

#define ZTK_WINDOW_STATE_NONE 0x0
#define ZTK_WINDOW_STATE_DEFINED 0x1
#define ZTK_WINDOW_STATE_REGISTERED 0x2
#define ZTK_WINDOW_STATE_CREATED 0x4
#define ZTK_WINDOW_STATE_OPENED 0x8
#define ZTK_WINDOW_STATE_RUNNING 0x10
#define ZTK_WINDOW_STATE_EXITING 0x40
#define ZTK_WINDOW_STATE_DESTROYED 0x80
#define ZTK_WINDOW_STATE_KEYFOCUS 0x10000000
#define ZTK_WINDOW_STATE_MINIMIZED 0x20000000
#define ZTK_WINDOW_STATE_SHOW 0x40000000
#define ZTK_WINDOW_STATE_ACTIVATED 0x80000000

#define ZTK_WINDOW_TYPE_UNKNOWN 0x0
#define ZTK_WINDOW_TYPE_WIN32 0x1
#define ZTK_WINDOW_TYPE_WIN64 0x100

#define ZTK_WINDOW_INPUT_CHAR 0x1

#define ZTK_WINDOW_IDLE_ENABLED 0x1
#define ZTK_WINDOW_IDLE_ALLOWED 0x2
#define ZTK_WINDOW_IDLE_HOLDOFF 0x4
#define ZTK_WINDOW_IDLE_AUTOMATIC 0x8

#define ZTK_WINDOW_BLENDMODE_BLOT 0x0
#define ZTK_WINDOW_BLENDMODE_ALPHA 0x1

#define ZTK_WINDOW_BACKGROUND_AUTO 0x2
#define ZTK_WINDOW_BACKGROUND_ENABLED 0x1
#define ZTK_WINDOW_BACKGROUND_NONE 0x0

#endif // ZTK__DEFINES_H_INCLUDED
