/*** Copyright (C) 2019-2025 ZaidaTek, Andreas Riebesehl
**** This work is licensed under: Creative Commons Attribution-NoDerivatives 4.0 International Public License
**** For full license text, please visit: https://creativecommons.org/licenses/by-nd/4.0/legalcode
***/
#ifndef ZTK__DEFINES_H_INCLUDED
#define ZTK__DEFINES_H_INCLUDED

///export all this to __runtime, and delete this file

#define ZTK_FLAG_NONE 0x0
#define ZTK_KEY_SIZE_LENGTH 0x100
#define ZTK_KEY_SIZE_SHIFT 5
#define ZTK_KEY_SIZE_UNIT 32
#define ZTK_KEY_SIZE_UNITS (ZTK_KEY_SIZE_LENGTH / ZTK_KEY_SIZE_UNIT)
#define ZTK_BLENDMODE_BLOT 0x0
#define ZTK_BLENDMODE_ALPHA 0x1
#define ZTK_DRAW_FLAG_NONE ZTK_FLAG_NONE
#define ZTK_DRAW_FLAG_ENABLED 0x1
#define ZTK_DRAW_FLAG_UNBUFFERED 0x10
#define ZTK_DRAW_TYPE_SPRITE 0x1
#define ZTK_DRAW_TYPE_SURFACE 0x2
#define ZTK_DRAW_TYPE_TEXT 0x4
#define ZTK_DRAW_TYPE_TEXTCOPY 0x8
#define ZTK_WINDOW_INPUT_CHAR 0x1
#define ZTK_BUFFER_EVENT 16384
#define ZTK_BUFFER_DRAW 8192
#define ZTK_BUFFER_INPUT_TEXT 4
#define ZTK_DEFAULT_RENDERER ZTK_RENDERER_SYSTEM
#define ZTK_DEFAULT_EVENT_ENABLED ZTK_HID_ALL
#define ZTK_DEFAULT_EVENT_PUMP (ZTK_HID_MOUSE | ZTK_HID_KEY)
#define ZTK_DEFAULT_EVENT_FLAG ZTK_FLAG_NONE //(ZTK_EVENT_FLAG_SIMPLE)
//#define ZTK_DEFAULT_DRAW_FLAG (ZTK_DRAW_FLAG_ENABLED | ZTK_DRAW_FLAG_UNBUFFERED)
#define ZTK_DEFAULT_DRAW_FLAG ZTK_DRAW_FLAG_ENABLED
#define ZTK_DEFAULT_TIMER_RESOLUTION 1
#define ZTK_DEFAULT_TIMER_PUMP 5
#define ZTK_DEFAULT_INPUT_FLAG ZTK_FLAG_NONE

#endif // ZTK__DEFINES_H_INCLUDED
